import Head from "next/head";
import { useEffect, useState } from "react";
import ContainerPage from "/components/ContainerPage/ContainerPage";
import GitHub from "/components/Icons/GitHub";
import Avatar from "components/avatar/avatar";
import Logo from "components/Icons/Logo";

import { loginGitHub, logginState } from "/firebase/client";

const Home = () => {
  const [user, setUser] = useState(null);
  useEffect(() => {
    logginState(setUser);
  }, []);
  const handleLogin = () => {
    loginGitHub()
      .then((userLogged) => {
        setUser(userLogged);
        return;
      })
      .catch(console.log);
    return;
  };
  return (
    <ContainerPage>
      <Head>
        <meta charSet="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Luna</title>
      </Head>
      <section className="w-full h-full flex flex-col items-center justify-center ">
        <Logo size={100}/>
        <h3 className="text-center text-4xl font-bold m-2">Luna</h3>
        <p className="m-2">Inspired by Twitter</p>
        {user ? (
          <Avatar avatar={user.avatar} avatarSize={40} name={user.name} />
        ) : (
          <button
            onClick={handleLogin}
            className="flex items-center text-neutral-100 p-2 m-2 bg-neutral-900 rounded-xl"
          >
            <div className="mr-2">
              <GitHub />
            </div>
            Login with GitHub
          </button>
        )}
      </section>
    </ContainerPage>
  );
};

export default Home;
