import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import ContainerPage from "/components/ContainerPage/ContainerPage";
import GitHub from "/components/Icons/GitHub";
import Logo from "components/Icons/Logo";

import { loginGitHub } from "/firebase/client";
import useUser, { USER_STATES } from "hooks/useUser";

const Home = () => {
  const router = useRouter();
  const { user } = useUser();
  useEffect(() => {
    user.status === USER_STATES.IS_LOGGED && router.replace("/home");
  }, [user]);
  const handleLogin = () => {
    loginGitHub().catch(console.log);
    return;
  };
  return (
    <ContainerPage>
      <Head>
        <meta charSet="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Luna</title>
      </Head>
      <section className="w-full h-full flex flex-col items-center justify-center ">
        <Logo size={100} priorityimg={true} />
        <h3 className="text-center text-4xl font-bold m-2">Luna</h3>
        <p className="m-2">Inspired by Twitter</p>
        {/* show loading messsage if: */}
        {user.status === USER_STATES.NOT_LOGGED && (
          <span className="text-lg">Cargando...</span>
        )}
        {/* show loggin button if: */}
        {user.status === USER_STATES.UNKNOW && (
          <button
            onClick={handleLogin}
            className="flex items-center text-neutral-100 p-2 m-2 bg-neutral-900 rounded-xl"
          >
            <div className="mr-2">
              <GitHub />
            </div>
            Login with GitHub
          </button>
        )}
      </section>
    </ContainerPage>
  );
};

export default Home;
