import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

import Logo from "components/Icons/Logo";
import useUser from "hooks/useUser";
import { USER_STATES } from "CONSTANTS/USER_STATES";
import { loginGitHub } from "Firebase/login/login";
import LoginWithGitHub from "components/Buttons/LoginWithGitHub";

const Home = () => {
  const router = useRouter();
  const { user } = useUser();
  useEffect(() => {
    user.status === USER_STATES.IS_LOGGED && router.replace("/home");
  }, [user]);
  const handleLoginGitHub = () => {
    loginGitHub().catch(console.log);
    return;
  };
  return (
    <>
      <Head>
        <meta charSet="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Luna</title>
      </Head>
      <section className="w-full h-full flex flex-col items-center justify-center ">
        <Logo size={100} priorityimg={true} />
        <h3 className="text-center text-4xl font-bold m-2">Luna</h3>
        <p className="m-2">Inspired by Twitter</p>
        {user.status === USER_STATES.VERIFYING && (
          <span className="text-lg">Verifying login...</span>
        )}
        {user.status === USER_STATES.UNKNOW ||
          (user.status === USER_STATES.NOT_LOGGED && (
            <LoginWithGitHub handleClick={handleLoginGitHub} />
          ))}
      </section>
    </>
  );
};

export default Home;
