import Head from "next/head";
import { useEffect, useState } from "react";

import Avatar from "components/avatar/avatar";
import TweetCard from "components/Tweet/TweetCard";
import Navigation from "components/Navigation/Navigation";
import useUser, { USER_STATES } from "hooks/useUser";
import { listenLatestTweets } from "/firebase/client";
import { filterTweetData } from "helpers/front/tweets/tweetData";

const Home = () => {
  const { user } = useUser();
  const [timeline, setTimeline] = useState({});
  useEffect(() => {
    let unsubscribe = false;
    if (user.status === USER_STATES.IS_LOGGED) {
      unsubscribe = listenLatestTweets((docs) => {
        const tweets = docs.map((doc) => {
          return filterTweetData(doc.id, doc.data());
        });
        setTimeline({ tweets });
      });
    }
    return () => unsubscribe && unsubscribe();
  }, [user]);
  return (
    <>
      <Head>
        <meta charSet="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Luna - Home</title>
      </Head>
      <section className="w-full min-h-full">
        <header className="p-2 sticky top-0 left-0 flex justify-between bg-neutral-200/75 backdrop-blur-sm">
          <div className="w-16 flex items-center justify-center">
            {user.status === USER_STATES.IS_LOGGED && (
              <Avatar avatar={user.avatar} avatarSize={35} />
            )}
          </div>
          <div className="w-full flex items-center">
            <h2 className="text-xl font-bold ml-2">Home</h2>
          </div>
          <div className="w-16 flex items-center justify-center"></div>
        </header>
        {/*Tweets*/}
        <section>
          {timeline.tweets &&
            timeline.tweets.map((tweet) => (
              <TweetCard
                key={tweet.id}
                id={tweet.id}
                uid={tweet.uid}
                name={tweet.name}
                avatar={tweet.avatar}
                at={tweet.at}
                date={tweet.date}
                content={tweet.content}
              />
            ))}
        </section>
        <p className="text-lg text-center mt-6 text-neutral-500">
          Esto es todo por el momento :(
        </p>
      </section>
      <Navigation />
    </>
  );
};

export default Home;
