import Head from "next/head";
import { useEffect, useState } from "react";
import ContainerPage from "/components/ContainerPage/ContainerPage";
import Avatar from "components/avatar/avatar";
import Logo from "components/Icons/Logo";

import { logginState } from "/firebase/client";
import Tweet from "components/Tweet/Tweet";

const Home = () => {
  const [user, setUser] = useState(null);
  const [timeline, setTimeline] = useState(null);
  useEffect(() => {
    logginState(setUser);
    fetch("/api/statuses/HomeTimeline")
      .then((res) => res.json())
      .then(setTimeline)
      .catch(console.log);
  }, []);
  return (
    <ContainerPage>
      <Head>
        <meta charSet="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Luna</title>
      </Head>
      <section className="w-full h-full">
        <header className="p-2 sticky top-0 left-0 flex justify-between bg-neutral-200/75 backdrop-blur-sm">
          <div className="w-16 flex items-center justify-center">
            {user && <Avatar avatar={user.avatar} avatarSize={35} />}
          </div>
          <div className="w-full flex items-center">
            <h2 className="text-xl font-bold ml-2">Home</h2>
          </div>
          <div className="w-16 flex items-center justify-center"></div>
        </header>
        {/*Tweets*/}
        <section>
          {timeline &&
            timeline.map((tweet) => (
              <Tweet key={tweet.id} tweetContent={tweet} />
            ))}
        </section>
      </section>
    </ContainerPage>
  );
};

export default Home;
