import Head from "next/head";
import { useEffect, useState } from "react";

import TweetCard from "components/Tweet/TweetCard";
import Navigation from "components/Navigation/Navigation";
import useUser from "hooks/useUser";
import { listenLatestTweets } from "Firebase/database/actions";
import { filterTweetData } from "helpers/front/tweets/tweetData";
import { USER_STATES } from "CONSTANTS/USER_STATES";
import UserMenu from "components/Navigation/UserMenu";
import HomeHeader from "components/Header/HomeHeader";
import {ModalProvider} from "context/Modal";

const Home = () => {
  const { user } = useUser();
  const [timeline, setTimeline] = useState({});
  useEffect(() => {
    let unsubscribe = false;
    if (user.status === USER_STATES.IS_LOGGED) {
      unsubscribe = listenLatestTweets((docs) => {
        const tweets = docs.map((doc) => {
          return filterTweetData(doc.id, doc.data());
        });
        setTimeline({ tweets });
      });
    }
    return () => unsubscribe && unsubscribe();
  }, [user]);
  return (
    <div className="h-full">
      <Head>
        <meta charSet="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Luna - Home</title>
      </Head>
      <section className="w-full h-full">
        <ModalProvider>
          {user.status === USER_STATES.IS_LOGGED && <HomeHeader user={user} />}
          {user.status === USER_STATES.IS_LOGGED && <UserMenu user={user} />}
        </ModalProvider>
        {/*Tweets*/}
        <section className="w-full h-full">
          {timeline.tweets &&
            timeline.tweets.map((tweet) => (
              <TweetCard
                key={tweet.id}
                id={tweet.id}
                uid={tweet.uid}
                name={tweet.name}
                avatar={tweet.avatar}
                at={tweet.at}
                date={tweet.date}
                content={tweet.content}
              />
            ))}
          <p className="text-lg text-center mt-6 text-neutral-500">
            {"Esto es todo por el momento :("}
          </p>
        </section>
        <Navigation />
      </section>
    </div>
  );
};

export default Home;
