import Head from "next/head";
import ContainerPage from "/components/ContainerPage/ContainerPage";

import useUser, { USER_STATES } from "hooks/useUser";
import CreateTweet from "components/CreateTweet/CreateTweet";

const TweetPage = () => {
  const { user } = useUser();
  return (
    <ContainerPage>
      <Head>
        <meta charSet="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Luna</title>
      </Head>
      <section className="w-full min-h-full">
        <header className="p-2 sticky top-0 left-0  bg-neutral-200/75">
          <div className="w-16 flex items-center justify-center">{"<-"}</div>
        </header>
        <section>
          {user.status === USER_STATES.IS_LOGGED && <CreateTweet user={user} />}
        </section>
      </section>
    </ContainerPage>
  );
};

export default TweetPage;
