import Head from "next/head";

import useUser from "hooks/useUser";
import CreateTweet from "components/CreateTweet/CreateTweet";
import Header from "components/Header/Header";
import { USER_STATES } from "CONSTANTS/USER_STATES";

const TweetPage = () => {
  const { user } = useUser();
  return (
    <>
      <Head>
        <meta charSet="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Luna</title>
      </Head>
      <section className="w-full min-h-full">
        <Header pageName="Create Tweet" />
        <section>
          {user.status === USER_STATES.IS_LOGGED && <CreateTweet user={user} />}
        </section>
      </section>
    </>
  );
};

export default TweetPage;
